### ISSUE TITLE
rungb.jl not found

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/GenieBuilderIssues#1]
SystemError: opening file "D:\\Documents\\Nutstore\\Code\\Julia\\rungb.jl": No such file or directory

**Comment by essenciary** [comment]
Based on a different issue, seems to be caused by `cd` - maybe set up in the `startup.jl` file. We're fixing it by ignoring the `startup.jl` file.

**Comment by optikc** [comment]
`cd`  is not used in my `startup.jl`. The VSCode automatically switches the directory to the current folder, which is `D:\Documents\Nutstore\Code\Julia`.

**Comment by essenciary** [comment]
@optikc did you configure VSCode to do that or why does it happen?

**Comment by optikc** [comment]
> @optikc did you configure VSCode to do that or why does it happen?

Sorry, I made a mistake. Now, the error is following:
LoadError: IOError: mkdir("C:\\Users\\Admin\\.julia\\geniebuilder"; mode=0o777): no such file or directory (ENOENT)

I have modified the .julia folder path
