### ISSUE TITLE
Error message on newly created app

### ISSUE THREAD

**Issue by juliohm** [GenieFramework/GenieBuilderIssues#10]
![image](https://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/assets/3345261/d8dc1756-f12a-47da-a39b-4f0b89a11627)

**Comment by essenciary** [comment]
Thanks for reporting this, we also have it in our backlog, working on it.

**Comment by essenciary** [comment]
This is solved - please try the latest version of GenieFramework.jl (1.20) and of the VSCode plugin. 

<img width="758" alt="image" src="https://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/assets/11292378/cd7e717f-b8c9-4011-b0dc-6127625d4a00">

If you still encounter it please provide the following details: 
* output of `julia> versioninfo()`
* output of `pkg> st`
* is this local GenieBuilder or GenieCloud? If local, os info.

**Comment by essenciary** [comment]
Closing, please reopen if not solved.
