### ISSUE TITLE
After error the app can't reload

### ISSUE THREAD

**Issue by juliohm** [GenieFramework/GenieBuilderIssues#11]
If we make any mistake during the development of app.jl that causes an error, the builder reaches a non-usable state:

![image](https://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/assets/3345261/96ccddf5-c446-4920-90f0-352942d45582)

I tried commenting the offending line in the app.jl and refreshing but nothing happened. Had to stop and restart the app, which is a bit time consuming.

**Comment by essenciary** [comment]
@juliohm That should not be the case. 

Can you provide a minimum example of a faulty app (just export it from GenieBuilder).

**Comment by juliohm** [comment]
Hi @essenciary! Unfortunately we don't have the MWE. I will close the issue.
