### ISSUE TITLE
Add option to avoid starting no-code editor automatically

### ISSUE THREAD

**Issue by juliohm** [GenieFramework/GenieBuilderIssues#12]
Whenever we start an app, a new tab is opened with the no-code editor. This can be annoying to some people that are already editing the app.jl.

**Comment by essenciary** [comment]
@protozoo valid request for one of the upcoming releases.

**Comment by protozoo** [comment]
We could add a setting for this

**Comment by juliohm** [comment]
Thank you all for the help. Feel free to reopen the issue if someone needs this feature.
