### ISSUE TITLE
Option for add new routes in Builder

### ISSUE THREAD

**Issue by PharmCat** [GenieFramework/GenieBuilderIssues#6]
I have added:

```
Page("/samplen", view = "views/samplen.jl.html",
        layout = "layouts/app.jl.html",
        model = () -> AppModel |> init_from_storage |> AppModels.handlers,
        context = @__MODULE__)
```
into routes.jl

and add `views/samplen.jl.html`

but nothing happens: 404 Not Found

**Comment by essenciary** [comment]
Sorry about the very late reply! This somehow fell through the cracks. I hope it was not an issue though, as it should work out of the box. Maybe there some other error stopping the code from recompiling correctly. Please check the logs. 

<img width="861" alt="image" src="https://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/assets/11292378/2ef107d6-e371-4bfe-ab00-5483d810faa0">

Closing, feel free to reopen if not solved.

**Comment by essenciary** [comment]
And of course, you can also use the `@page` macro which is the recommended way.
