### ISSUE TITLE
Genie Builder first server start issue

### ISSUE THREAD

**Issue by omulan** [GenieFramework/GenieBuilderIssues#9]
Hello, 
I have just installed the Genie Builder extension and I get the following error when starting the server
<img width="791" alt="image" src="https://user-images.githubusercontent.com/2410597/233830046-b60db5b1-035c-4ce5-9196-abafd045b60c.png">

**Comment by essenciary** [comment]
Thanks, looking into it

**Comment by protozoo** [comment]
@omulan We fixed the problem in v0.3.38. Please can you update and try again? Closing this issue as it works now in our tests. Please reopen if it still persists for you. Thank you!
